name: junglegym
description: "jungle gym platform"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  pinput: ^5.0.0
  get_storage: ^2.1.1
  intl_phone_field: ^3.2.0
  loading_animation_widget: ^1.3.0
  get: ^4.6.6
  dio: ^5.7.0
  fluttertoast: ^8.2.8
  carousel_slider: ^5.0.0
  local_auth: ^2.3.0
  intl_phone_number_input: ^0.7.4
  smart_auth: ^2.0.0
  mailer: ^6.4.1
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/


